### PR TITLE
Adding the ability to ignore unstaged changes

### PR DESCRIPTION
**Pull request by DanCardin**
The default behavior doesn't work particularly well when combining this tool with git pre-commit hooks, since considering unstaged changes isn't really what you would want.

### CODE REVIEW

**Comment by Bachmann1234** [comment]
@DanCardin howdy! Thanks, ill take a look at this later.

Dont worry about the build failing, That is a bug I have fixed in my fork that I will merge in here soon.

**Comment by Bachmann1234** [comment]
Alrighty! 

I updated master, if you rebase from it the build should pass

I like the feature but it needs a bit of work before I can merge it.

First, it needs some test code. I really can't merge this without tests.

Second, can I convince you to put this feature onto diff-cover as well as diff-quality? This feature is less likely to be used for coverage I suspect, but consistency in arguments where possible would be nice.

**Comment by DanCardin** [comment]
yep, and yep. ill try to get to this tomorrow.

**Comment by Bachmann1234** [comment]
One more thing, don't forget to add your name to the authors file if you would like https://github.com/edx/diff-cover/blob/master/AUTHORS

We are currently in the process of transitioning to my fork https://github.com/Bachmann1234/diff-cover being the main repo. But don't worry, since you started on this repo I can handle moving it over once I get it merged in.

**Comment by DanCardin** [comment]
Done!

**Comment by Bachmann1234** [comment]
This has been released https://pypi.python.org/pypi/diff_cover/0.7.4

**Pull request merged**
