### PR TITLE
Issue 133 Parse pylint duplicate code violation

### PR DESCRIPTION
**Pull request by Bachmann1234**
attempting to fix https://github.com/edx/diff-cover/issues/133

**THIS IS NOT TO BE MERGED**. Close though. I need some help from @wedaly 

So this code works for my test but fails on ```test_quality``` in ```test_violations_reporter.py```

I think the test is incorrect but I wanted to check with you as git blame has you touching this last

The test shows pylint giving this output
```
file1.py:162: [R0801] Similar lines in 2 files
            ==external_auth.views:1
            ==student.views:4
```

It looks to me like this test was crafted by taking pylint output from some other project (edx-platform?) and modifying it. 

It seems wrong that neither of the two files pylint is flagging is file1.py. Do you have any memory of this at all?

### CODE REVIEW

**Comment by Bachmann1234** [comment]
On another note: I find this solution fragile. It will break if pylint changes their output format. I don't think this is entirely avoidable. Think I could get away with printing a warning when the file does not parse as I expect?

**Comment by Bachmann1234** [comment]
This PR also have some changes I have in my repo. @nedbat was discussing making mine the official. Is that something that is still happening? If not I can get rid of my fork. 

Either way ill reopen this PR without those changes after I hear back from you

**Comment by wedaly** [comment]
Hi @Bachmann1234 , I have a very fuzzy memory of copying that output from pylint running on edx-platform.  I may have tried to include extra lines (without violations) to verify that the pylint regex would ignore those.  I suspect there's a more robust way to set this up (maybe running pylint itself in an integration test).

We still want to make your fork the official fork.  A few weeks ago, I merged a PR into edx-platform to install diff-cover from pypi instead of from this repo.  I guess I'm not sure what next steps to take -- would it make sense to update the README in edx/diff-cover to say something along the lines of "Go to Matt's repo for the official version?"

**Comment by Bachmann1234** [comment]
@wedaly Ok, so ill update the test to do what i expect and merge the code into my master and release from there.

**Pull request closed without merging**
